FEATURE: [grid2] recover with twin orders
c9s/bbgo pull request #1174
Opened 2023-05-22 07:06 UTC by kbearXD

2023-05-23 08:38 UTC, c9s requested changes
This CR also prevents merge

2023-05-23 08:38 UTC, c9s requested changes
This CR also prevents merge

2023-06-14 03:23 UTC, gx578007 approved these changes

2023-06-14 05:01 UTC, c9s approved these changes

2023-06-14 05:02 UTC, merged